In [49]:
def im2col(X, filter, stride=1, padH=0, padW=0):
    N, C, H, W = X.shape
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    img = np.pad(X, [(0, 0), (0, 0), (padH, padH), (padW, padW)], 'constant')
    cols = np.zeros([N, C, filter_h * filter_w, out_h * out_w])
    for h in range(filter_h):
        h_max = h + stride * out_h
        for w in range(filter_w):
            w_max = w + stride * out_w
            crop = img[:, :, h:h_max:stride, w:w_max:stride]
            crop = crop.reshape([img.shape[0], img.shape[1], -1])
            cols[:, :, h, :] = crop
    cols = cols.reshape([cols.shape[0],cols.shape[1] * cols.shape[2], -1])
    cols = cols.transpose([0,2,1])
    return cols

def conv2d(X, filter, padding='valid', stride=1, pad=0):
    N, C, H, W = X.shape
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    if padding == 'valid':
        padH, padW = pad, pad
    elif padding == 'same':
        padH = ((H - 1) * (stride - 1) + filter_h - 1) // 2
        padW = ((W - 1) * (stride - 1) + filter_w - 1) // 2
    else:
        raise ValueError('padding value error')
    
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    colX = im2col(X, filter, stride, padH, padW)
    print(colX.shape)
    colFilter = np.reshape(filter, [-1, filter.shape[3]])
    print(colFilter.shape)
    y = np.dot(colX, colFilter)
    y = np.transpose(y, [0, 2, 1])
    print(y.shape)
    y = y.reshape([y.shape[0], y.shape[1], out_h, out_w])
    
    
    _w = np.reshape(filter, (filter.shape[0]*filter.shape[1]*filter.shape[2], filter.shape[3]))
    print(_w.shape)
    _colX = np.expand_dims(colX, 3)
    for i in range(_w.shape[1]):
        print(i)
        _wi = np.expand_dims(_w[:, i], 0)
        print('!', np.dot(_colX, _wi).shape)
        
    #print(_colX.shape)
    #print(np.dot(_colX, _w).shape)
    
    return y
    
def gradient_check(op, X, w, delta=1e-5):
    y1 = op(X, w)
    y2 = op(X, w+delta)
    print((y2 - y1) / delta)
    
    

In [50]:
import numpy as np

X = np.random.random([100,3,50,50])
w = np.random.random([3,3,3,64])
#col = im2col2(X,w)
y = conv2d(X, w, padding='same')
#gradient_check(conv2d, X, w)
print(y.shape)

(100, 2500, 27)
(27, 64)
(100, 64, 2500)
(27, 64)
0
('!', (100, 2500, 27, 27))
1
('!', (100, 2500, 27, 27))
2
('!', (100, 2500, 27, 27))
3
('!', (100, 2500, 27, 27))
4
('!', (100, 2500, 27, 27))
5
('!', (100, 2500, 27, 27))
6
('!', (100, 2500, 27, 27))
7
('!', (100, 2500, 27, 27))
8
('!', (100, 2500, 27, 27))
9
('!', (100, 2500, 27, 27))
10
('!', (100, 2500, 27, 27))
11
('!', (100, 2500, 27, 27))
12
('!', (100, 2500, 27, 27))
13
('!', (100, 2500, 27, 27))
14
('!', (100, 2500, 27, 27))
15
('!', (100, 2500, 27, 27))
16
('!', (100, 2500, 27, 27))
17
('!', (100, 2500, 27, 27))
18
('!', (100, 2500, 27, 27))
19
('!', (100, 2500, 27, 27))
20
('!', (100, 2500, 27, 27))
21
('!', (100, 2500, 27, 27))
22
('!', (100, 2500, 27, 27))
23
('!', (100, 2500, 27, 27))
24
('!', (100, 2500, 27, 27))
25
('!', (100, 2500, 27, 27))
26
('!', (100, 2500, 27, 27))
27
('!', (100, 2500, 27, 27))
28
('!', (100, 2500, 27, 27))
29
('!', (100, 2500, 27, 27))
30
('!', (100, 2500, 27, 27))
31
('!', (100, 2500, 27, 27))


In [53]:
a = np.random.random([4,4])
a = a.flatten()
print(a.shape)

(16L,)


In [31]:
X = np.random.random([100,3])
w = np.random.random([3,50])
y = np.dot(X, w)
print(y.shape)

(100, 50)


In [130]:
def im2col(X, filter, stride=1, padH=0, padW=0):
    N, C, H, W = X.shape
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    print(out_h, out_w)
    img = np.pad(X, [(0, 0), (0, 0), (padH, padH), (padW, padW)], 'constant')
    cols = np.zeros([N, C, filter_h * filter_w, out_h * out_w])
    print(cols.shape)
    for h in range(filter_h):
        h_max = h + stride * out_h
        for w in range(filter_w):
            w_max = w + stride * out_w
            crop = img[:, :, h:h_max:stride, w:w_max:stride]
            #print(crop)
            crop = crop.reshape([img.shape[0], img.shape[1], -1])
            cols[:, :, h*filter_w + w, :] = crop
    cols = cols.reshape([cols.shape[0],cols.shape[1] * cols.shape[2], -1])
    cols = cols.transpose([0,2,1])
    return cols


def col2im(X, filter, image_size, stride=1):
    out_N, out_C, out_H, out_W = image_size
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    img = np.zeros(image_size)
    weight = np.zeros(image_size)
    
    X = X.transpose([0,2,1])
    X = X.reshape([X.shape[0], out_C, X.shape[1]/out_C, X.shape[2]])
    print('\n')
    print(X.shape)
    k = 0
    for h in range(0, img.shape[2]-filter_h+1, stride):
        for w in range(0, img.shape[3]-filter_w+1, stride):
            #print(img[:, :, h:h+filter_h, w:w+filter_w].shape)
            #print(X[:,:,:,0].shape)
            img[:, :, h:h+filter_h, w:w+filter_w] += X[:,:,:,k].reshape([X.shape[0], X.shape[1], filter_h, filter_w])
            weight[:, :, h:h+filter_h, w:w+filter_w] += np.ones(([X.shape[0], X.shape[1], filter_h, filter_w]))
            k += 1
    return img / weight
        


In [139]:
import numpy as np
X = np.random.random([2,2,5,6])
print(X)
w = np.random.random([3,3,1,64])
col = im2col(X,w,stride=1)
#print(col)
img = col2im(col, w, [2,2,5,6], stride=1)
print(img)

[[[[  3.86665220e-01   4.56998540e-01   8.99639808e-01   8.27772132e-01
      8.12482129e-01   7.50578792e-01]
   [  9.45241348e-01   1.86010903e-01   3.75942173e-01   4.58893397e-01
      1.43027442e-01   9.43629231e-02]
   [  3.74528437e-01   2.47095608e-01   4.53263398e-01   9.22766141e-02
      7.87503412e-01   8.81937755e-01]
   [  4.06988386e-02   8.92616301e-02   8.12669040e-01   3.83178149e-01
      4.41646464e-01   1.17539307e-01]
   [  5.43091799e-01   3.40321242e-01   1.88128629e-02   3.59770674e-01
      2.62045909e-01   5.98912940e-01]]

  [[  2.81434569e-01   5.16794912e-01   4.63708729e-01   6.50596373e-01
      2.80680198e-01   5.56315072e-01]
   [  4.89248815e-01   5.10305869e-01   8.85398871e-01   8.49894604e-01
      7.97185386e-01   8.01776258e-01]
   [  4.71966177e-04   5.04371598e-01   4.82841667e-01   3.17065336e-01
      9.53620297e-01   8.87726148e-01]
   [  6.48420789e-02   4.59248760e-01   3.84889563e-01   2.84918769e-01
      6.94344848e-01   8.43408731e-01]

In [135]:
print(X)
print(img)

[[[[ 0.28879044  0.37086901  0.03752553  0.13725906  0.9837876   0.91849584]
   [ 0.49939521  0.107       0.86833885  0.69911543  0.38529969  0.24823558]
   [ 0.81534475  0.9658977   0.82562689  0.2832025   0.19396303  0.57435432]
   [ 0.37627691  0.58881225  0.90352901  0.56831081  0.6162882   0.92626676]
   [ 0.25989764  0.7362692   0.92058804  0.39475474  0.85264035  0.44648256]]]]
[[[[ 0.28879044  0.37086901  0.03752553  0.13725906  0.9837876   0.91849584]
   [ 0.49939521  0.107       0.86833885  0.69911543  0.38529969  0.24823558]
   [ 0.81534475  0.9658977   0.82562689  0.2832025   0.19396303  0.57435432]
   [ 0.37627691  0.58881225  0.90352901  0.56831081  0.6162882   0.92626676]
   [ 0.25989764  0.7362692   0.92058804  0.39475474  0.85264035  0.44648256]]]]
