In [49]:
def im2col(X, filter, stride=1, padH=0, padW=0):
    N, C, H, W = X.shape
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    img = np.pad(X, [(0, 0), (0, 0), (padH, padH), (padW, padW)], 'constant')
    cols = np.zeros([N, C, filter_h * filter_w, out_h * out_w])
    for h in range(filter_h):
        h_max = h + stride * out_h
        for w in range(filter_w):
            w_max = w + stride * out_w
            crop = img[:, :, h:h_max:stride, w:w_max:stride]
            crop = crop.reshape([img.shape[0], img.shape[1], -1])
            cols[:, :, h, :] = crop
    cols = cols.reshape([cols.shape[0],cols.shape[1] * cols.shape[2], -1])
    cols = cols.transpose([0,2,1])
    return cols

def conv2d(X, filter, padding='valid', stride=1, pad=0):
    N, C, H, W = X.shape
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    if padding == 'valid':
        padH, padW = pad, pad
    elif padding == 'same':
        padH = ((H - 1) * (stride - 1) + filter_h - 1) // 2
        padW = ((W - 1) * (stride - 1) + filter_w - 1) // 2
    else:
        raise ValueError('padding value error')
    
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    colX = im2col(X, filter, stride, padH, padW)
    print(colX.shape)
    colFilter = np.reshape(filter, [-1, filter.shape[3]])
    print(colFilter.shape)
    y = np.dot(colX, colFilter)
    y = np.transpose(y, [0, 2, 1])
    print(y.shape)
    y = y.reshape([y.shape[0], y.shape[1], out_h, out_w])
    
    
    _w = np.reshape(filter, (filter.shape[0]*filter.shape[1]*filter.shape[2], filter.shape[3]))
    print(_w.shape)
    _colX = np.expand_dims(colX, 3)
    for i in range(_w.shape[1]):
        print(i)
        _wi = np.expand_dims(_w[:, i], 0)
        print('!', np.dot(_colX, _wi).shape)
        
    #print(_colX.shape)
    #print(np.dot(_colX, _w).shape)
    
    return y
    
def gradient_check(op, X, w, delta=1e-5):
    y1 = op(X, w)
    y2 = op(X, w+delta)
    print((y2 - y1) / delta)
    
    

In [50]:
import numpy as np

X = np.random.random([100,3,50,50])
w = np.random.random([3,3,3,64])
#col = im2col2(X,w)
y = conv2d(X, w, padding='same')
#gradient_check(conv2d, X, w)
print(y.shape)

(100, 2500, 27)
(27, 64)
(100, 64, 2500)
(27, 64)
0
('!', (100, 2500, 27, 27))
1
('!', (100, 2500, 27, 27))
2
('!', (100, 2500, 27, 27))
3
('!', (100, 2500, 27, 27))
4
('!', (100, 2500, 27, 27))
5
('!', (100, 2500, 27, 27))
6
('!', (100, 2500, 27, 27))
7
('!', (100, 2500, 27, 27))
8
('!', (100, 2500, 27, 27))
9
('!', (100, 2500, 27, 27))
10
('!', (100, 2500, 27, 27))
11
('!', (100, 2500, 27, 27))
12
('!', (100, 2500, 27, 27))
13
('!', (100, 2500, 27, 27))
14
('!', (100, 2500, 27, 27))
15
('!', (100, 2500, 27, 27))
16
('!', (100, 2500, 27, 27))
17
('!', (100, 2500, 27, 27))
18
('!', (100, 2500, 27, 27))
19
('!', (100, 2500, 27, 27))
20
('!', (100, 2500, 27, 27))
21
('!', (100, 2500, 27, 27))
22
('!', (100, 2500, 27, 27))
23
('!', (100, 2500, 27, 27))
24
('!', (100, 2500, 27, 27))
25
('!', (100, 2500, 27, 27))
26
('!', (100, 2500, 27, 27))
27
('!', (100, 2500, 27, 27))
28
('!', (100, 2500, 27, 27))
29
('!', (100, 2500, 27, 27))
30
('!', (100, 2500, 27, 27))
31
('!', (100, 2500, 27, 27))


In [53]:
a = np.random.random([4,4])
a = a.flatten()
print(a.shape)

(16L,)


In [31]:
X = np.random.random([100,3])
w = np.random.random([3,50])
y = np.dot(X, w)
print(y.shape)

(100, 50)


In [42]:
def im2col(X, filter, stride=1, padH=0, padW=0):
    N, C, H, W = X.shape
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    img = np.pad(X, [(0, 0), (0, 0), (padH, padH), (padW, padW)], 'constant')
    cols = np.zeros([N, C, filter_h * filter_w, out_h * out_w])
    for h in range(filter_h):
        h_max = h + stride * out_h
        for w in range(filter_w):
            w_max = w + stride * out_w
            crop = img[:, :, h:h_max:stride, w:w_max:stride]
            #print(crop)
            crop = crop.reshape([img.shape[0], img.shape[1], -1])
            cols[:, :, h*filter_w + w, :] = crop
    cols = cols.reshape([cols.shape[0],cols.shape[1] * cols.shape[2], -1])
    cols = cols.transpose([0,2,1])
    return cols


def col2im(X, filter, image_size, stride=1):
    out_N, out_C, out_H, out_W = image_size
    filter_h, filter_w, filter_c, filter_c2 = filter.shape
    img = np.zeros(image_size)
    weight = np.zeros(image_size)
    
    X = X.transpose([0,2,1])
    X = X.reshape([X.shape[0], out_C, X.shape[1]/out_C, X.shape[2]])
    k = 0
    for h in range(0, img.shape[2]-filter_h+1, stride):
        for w in range(0, img.shape[3]-filter_w+1, stride):
            #print(img[:, :, h:h+filter_h, w:w+filter_w].shape)
            #print(X[:,:,:,0].shape)
            img[:, :, h:h+filter_h, w:w+filter_w] += X[:,:,:,k].reshape([X.shape[0], X.shape[1], filter_h, filter_w])
            weight[:, :, h:h+filter_h, w:w+filter_w] += np.ones(([X.shape[0], X.shape[1], filter_h, filter_w]))
            k += 1
    return img / weight
        


In [49]:
import numpy as np
X = np.random.random([5,2,20,20])
#print(X)
w = np.random.random([3,3,2,20])
col = im2col(X,w,stride=1, padH=1, padW=1)
print(col.shape)
img = col2im(col, w, [5,2,10,10])
print(img.shape)

(5, 400, 18)
(5, 2, 10, 10)


In [135]:
print(X)
print(img)

[[[[ 0.28879044  0.37086901  0.03752553  0.13725906  0.9837876   0.91849584]
   [ 0.49939521  0.107       0.86833885  0.69911543  0.38529969  0.24823558]
   [ 0.81534475  0.9658977   0.82562689  0.2832025   0.19396303  0.57435432]
   [ 0.37627691  0.58881225  0.90352901  0.56831081  0.6162882   0.92626676]
   [ 0.25989764  0.7362692   0.92058804  0.39475474  0.85264035  0.44648256]]]]
[[[[ 0.28879044  0.37086901  0.03752553  0.13725906  0.9837876   0.91849584]
   [ 0.49939521  0.107       0.86833885  0.69911543  0.38529969  0.24823558]
   [ 0.81534475  0.9658977   0.82562689  0.2832025   0.19396303  0.57435432]
   [ 0.37627691  0.58881225  0.90352901  0.56831081  0.6162882   0.92626676]
   [ 0.25989764  0.7362692   0.92058804  0.39475474  0.85264035  0.44648256]]]]


In [40]:
def im2col(X, filter_h, filter_w, stride=1, padH=0, padW=0):
    N, C, H, W = X.shape
    out_h = (H + 2 * padH - filter_h) // stride + 1
    out_w = (W + 2 * padW - filter_w) // stride + 1
    img = np.pad(X, [(0, 0), (0, 0), (padH, padH), (padW, padW)], 'constant')
    cols = np.zeros([N, C, filter_h * filter_w, out_h * out_w])
    for h in range(filter_h):
        h_max = h + stride * out_h
        for w in range(filter_w):
            w_max = w + stride * out_w
            crop = img[:, :, h:h_max:stride, w:w_max:stride]
            crop = crop.reshape([img.shape[0], img.shape[1], -1])
            cols[:, :, h*filter_w+w, :] = crop
    cols = cols.reshape([cols.shape[0], cols.shape[1] * cols.shape[2], -1])
    cols = cols.transpose([0, 2, 1])
    return cols
def maxpool(X, filter_h, filter_w, stride=2, pad=0):
        print(X.shape)
        N, C, H, W = X.shape
        padH = padW = pad
        out_h = (H + 2 * padH - filter_h) // stride + 1
        out_w = (W + 2 * padW - filter_w) // stride + 1
        print(X.shape)
        X_col = im2col(X, filter_h=filter_h, filter_w=filter_h,\
                       stride=stride, padH=padH, padW=padW)
        print(X_col.shape)
        X_col = X_col.transpose([0, 2, 1])
        X_col = X_col.reshape([X_col.shape[0], C, X_col.shape[1]/C, X_col.shape[2]])
        X_col = X_col.reshape([X_col.shape[0]*X_col.shape[1],X_col.shape[2], X_col.shape[3]])
        X_col = X_col.transpose([0, 2, 1]).reshape([X_col.shape[0]*X_col.shape[2], X_col.shape[1]])
        print(X_col.shape)
        '''
        print(X_col.shape)
        X_col = X_col.reshape([X_col.shape[0]*X_col.shape[1], X_col.shape[2]])
        X_col = X_col.reshape([X_col.shape[0], C, X_col.shape[1]/C])
        print(X_col.shape)
        X_col = X_col.reshape([X_col.shape[0]*X_col.shape[1], X_col.shape[2]])
        print(X_col.shape)
        '''
        max_idx = np.argmax(X_col, axis=1)
        print(max_idx.shape)
        out = X_col[range(X_col.shape[0]), max_idx]
        out = out.reshape([N, C, out_h, out_w])

        print(out.shape)
        return out


import numpy as np
a = np.random.random([2,2,5,5])
print(a)
b = maxpool(a, 2, 2)
print(b)
















[[[[ 0.68627306  0.41901478  0.29563456  0.71874872  0.30527756]
   [ 0.78460288  0.82599646  0.40191859  0.18639563  0.5160578 ]
   [ 0.38700714  0.03144271  0.19487395  0.26832222  0.78524844]
   [ 0.51920841  0.48273011  0.26155095  0.15793041  0.94398425]
   [ 0.50547014  0.32813951  0.98494355  0.43939105  0.85749928]]

  [[ 0.96208933  0.66019091  0.24485808  0.16804187  0.1345416 ]
   [ 0.82103221  0.8672245   0.32770332  0.01065596  0.56031591]
   [ 0.67236371  0.30802875  0.62664525  0.59037074  0.3835034 ]
   [ 0.45601298  0.43642314  0.28259094  0.57756424  0.2596144 ]
   [ 0.01915446  0.38755293  0.61781941  0.76997788  0.17615115]]]


 [[[ 0.41176456  0.91390609  0.44109974  0.01542018  0.61801703]
   [ 0.17528748  0.50984938  0.79370014  0.85623495  0.03732146]
   [ 0.4196113   0.52238052  0.37479398  0.91148155  0.93749422]
   [ 0.27868507  0.6541272   0.1439479   0.21757998  0.34983103]
   [ 0.95489583  0.65122854  0.55980921  0.84697162  0.70058541]]

  [[ 0.35969675  

In [55]:
a = np.array([[-1,1,0.3,2]])
print(np.maximum(0,a))

[[ 0.   1.   0.3  2. ]]
